### ISSUE TITLE
代码合并可能会报错，

### ISSUE THREAD

**Issue by lili21** [ArvoGuo/angular-lazy-click#1]
![2016-09-06 4 36 04](https://cloud.githubusercontent.com/assets/4456380/18266974/abbc4664-744f-11e6-83a5-4a3a45856362.png)

自执行函数问题，
如果像这样开始与结束没有加分号的话，碰到一个第三方库也没有加的话，合并代码的时候就会出错了

sc1.js

```
(function () {})()
```

sc2.js

```
(function () {}}()
```

合并结果

```
(function() {})()(function () {})()
```

解决方案

```
;(function () {})();
```

**Comment by ArvoGuo** [comment]
[fix ](https://github.com/ArvoGuo/angular-lazy-click/commit/348fce82697923c65c12d44a269bfd0eb801f364) @lili21
